"""Vertrag der Betriebssystem-Backends.

Das Programm importiert weiterhin ``autoclicker.winapi``. Dieses Modul ist nur
noch die stabile Fassade; die Implementierungen liegen hier nebenan.
"""

from typing import Protocol


class PlatformBackend(Protocol):
    """Vertrag für Eingabe, Fenster, Hotkeys und Bildschirmzugriff."""

    def get_screen_pixel(self, x: int, y: int): ...
    def install_mouse_hook(self, on_lbutton_down, on_wheel=None) -> bool: ...
    def remove_mouse_hook(self) -> None: ...
    def install_keyboard_hook(self, on_key_down) -> bool: ...
    def remove_keyboard_hook(self) -> None: ...
    def get_screen_size(self) -> tuple[int, int] | None: ...
    def get_virtual_desktop(self) -> tuple[int, int, int, int] | None: ...
    def get_virtual_origin(self) -> tuple[int, int]: ...
    def get_screen_center(self) -> tuple[int, int]: ...
    def get_cursor_pos(self) -> tuple[int, int]: ...
    def set_cursor_pos(self, x: int, y: int) -> bool: ...
    def send_click(self, x: int, y: int, move_delay: float = 0.01,
                   post_delay: float = 0.05) -> bool: ...
    def send_scroll(self, clicks: int, x: int | None = None,
                    y: int | None = None, move_delay: float = 0.01,
                    post_delay: float = 0.05) -> bool: ...
    def send_key(self, key_name: str) -> bool: ...
    def get_foreground_window_title(self) -> str: ...
    def is_target_window_active(self, title_substring: str) -> bool: ...
    def get_window_title_at(self, x: int, y: int) -> str: ...
    def register_hotkeys(self) -> bool: ...
    def poll_hotkey(self) -> int | None: ...
    def flush_hotkey_messages(self) -> None: ...
    def unregister_hotkeys(self) -> None: ...
    def liste_fenster(self) -> list: ...
    def get_client_rect_by_handle(self, handle: int): ...
    def resolve_window(self, title: str, instance: int = 0,
                       reference_rect=None): ...
    def get_client_rect_by_title(self, title_substring: str): ...
    def check_failsafe(self, state=None) -> bool: ...
    def get_current_thread_id(self) -> int: ...
    def post_quit(self, thread_id: int) -> None: ...
    def setze_app_id(self, app_id: str) -> bool: ...
    def setze_fenster_symbol(self, titel_substring: str,
                            warten: float = 0.0) -> bool: ...
    def platform_name(self) -> str: ...
    def environment_warnings(self) -> list[str]: ...
    def capture_screen(self, region=None): ...
    def capture_window(self, handle: int): ...
    def wait_for_key(self, names: tuple[str, ...],
                     timeout: float | None = 60.0): ...


# Die Fassade exportiert genau die Methoden des Vertrags. So kann keine neue
# Backend-Funktion in der Typbeschreibung landen, aber in der Laufzeitprüfung
# vergessen werden (oder umgekehrt).
BACKEND_FUNCTIONS = tuple(
    name for name, value in PlatformBackend.__dict__.items()
    if not name.startswith("_") and callable(value)
)
